apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-svc
  labels:
    app: udagram-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-feed
